name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List files
        run: ls ${{ github.workspace }}

      - name: NPM install
        run: npm install

      - name: Building Project
        run: npm run build

      - name: Deploy
        run: npm run deploy
        
      
